version: '3.8'
services:
  api:
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres
      PORT: 3000
      POSTGRES_HOST_AUTH_METHOD: trust
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['yarn', 'run', 'start:${NODE_ENV}']
    env_file:
      - .env
    ports:
      - 8080:3000
    depends_on:
      - postgres
    volumes:
      - .:/hovo-nest/src/app
      - /hovo-nest/src/app/node_modules
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: '${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${APP_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
    #   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
